# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee02c5d8d4e35e5747935c8516a241e2991a12935f1216e9bbea5b08e7a4e27c0f82edf89af2842766bba80880ccd705d7a2c158e6ab39e5e35e1ba7cf1f4467

test:
  secret_key_base: 5e046ca17f2d27a0934a80017dbcf6a3fe51ca91da6019fb1b72c00ce80ea0b659298aea6b91d70df7a20401c64fa651fa67ead0dd63e1d40e9c6524b52f9bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
